# dock_tempest
#
# Version: 0.0.1
# Desctiption: Openstack tempest testing in a docker container 	
#

FROM      ubuntu:14.04
MAINTAINER Keith Tobin <keith.tobin@gmail.com>

ENV PATH /usr/local/go/bin:$PATH 
